server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'mehisen'
    password: '123456'
    url: jdbc:postgresql://localhost:5432/fraud
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: 'true'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
